[irc]
alt_nicks = ["janus-test_", "janus-test__"]
nickname = "janus-test"
port = 6669
server = "acm.umn.edu"
use_ssl = true

[[bindings]]
discord = 509597195566317570 # https://discord.gg/RYjDWm7
irc = "#janus-test"
